apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pin-people-ingress
  namespace: pin-people
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - api.pinpeople.example.com
      secretName: pin-people-tls
  rules:
    - host: "api.pinpeople.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pin-people-service
                port:
                  number: 80
