apiVersion: v1
kind: Service
metadata:
  name: pin-people-service
  namespace: pin-people
spec:
  selector:
    app: pin-people-deployment
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
